Repository wafflestudio/wacruit-server, pull requests merged in 2023-07, with the labels that each got.

#8 make foreign key nullable for ON DELETE SET NULL & add migration test to CI
  .github/workflows/test.yaml
  wacruit/src/apps/problem/models.py
  wacruit/src/tests/conftest.py
Labels: fix

#6 Implement PATCH api for invitation email
  .env.test
  .github/workflows/test.yaml
  .pylintrc
  README.md
  poetry.lock
  pyproject.toml
  wacruit/src/app.py
  wacruit/src/apps/common/dependencies.py
  wacruit/src/apps/router.py
  wacruit/src/apps/user/models.py
  wacruit/src/apps/user/repositories.py
  wacruit/src/apps/user/schemas.py
  wacruit/src/apps/user/services.py
  wacruit/src/apps/user/views.py
  wacruit/src/database/base.py
  wacruit/src/secrets.py
  wacruit/src/settings.py
  wacruit/src/tests/conftest.py
  wacruit/src/tests/user/conftest.py
  wacruit/src/tests/user/test_user_service.py
  wacruit/src/tests/user/test_user_validation.py
Labels: enhancement

#7 Resume 모델 정의
  .gitignore
  wacruit/src/apps/resume/__init__.py
  wacruit/src/apps/resume/exceptions.py
  wacruit/src/apps/resume/models.py
  wacruit/src/apps/resume/repositories.py
  wacruit/src/apps/resume/schemas.py
  wacruit/src/apps/resume/services.py
  wacruit/src/apps/resume/views.py
  wacruit/src/apps/router.py
  wacruit/src/apps/user/models.py
  wacruit/src/apps/user/views.py
  wacruit/src/database/__init__.py
  wacruit/src/database/migrations/env.py
  wacruit/src/tests/resume/conftest.py
  wacruit/src/tests/resume/test_resume_service.py
Labels: enhancement

#11 채점 및 제출 결과 저장 로직 구현
  .github/workflows/test.yaml
  wacruit/src/apps/common/schemas.py
  wacruit/src/apps/judge/connections.py
  wacruit/src/apps/judge/repositories.py
  wacruit/src/apps/judge/schemas.py
  wacruit/src/apps/problem/exceptions.py
  wacruit/src/apps/problem/models.py
  wacruit/src/apps/problem/repositories.py
  wacruit/src/apps/problem/schemas.py
  wacruit/src/apps/problem/services.py
  wacruit/src/apps/problem/views.py
  wacruit/src/database/__init__.py
  wacruit/src/database/config.py
  wacruit/src/tests/models/conftest.py
  wacruit/src/tests/problem/conftest.py
  wacruit/src/tests/problem/test_problem_repository.py
Labels: enhancement

#15 fix scheme isssue of static file via kong-gateway
  wacruit/src/admin/__init__.py
  wacruit/src/admin/applications.py
  wacruit/src/app.py
Labels: fix

#20 fix migration file and env.py
  wacruit/src/apps/announcement/models.py
  wacruit/src/apps/common/sql.py
  wacruit/src/apps/problem/models.py
  wacruit/src/apps/resume/models.py
  wacruit/src/database/migrations/env.py
  wacruit/src/database/migrations/versions/2023_07_21_1823-3fdaee6050ce_initialize_database.py
  wacruit/src/database/migrations/versions/2023_07_22_0133-b06b459ca8b9_.py
Labels: fix

#21 add migration command on contiguous deployment
  .github/workflows/deploy-dev.yaml
  .github/workflows/deploy-prod.yaml
Labels: enhancement

#28 Testcase 리소스 제한 추가 외 기타 마이너 수정 사항
  wacruit/src/admin/formatters.py
  wacruit/src/admin/views.py
  wacruit/src/apps/judge/schemas.py
  wacruit/src/apps/problem/exceptions.py
  wacruit/src/apps/problem/models.py
  wacruit/src/apps/problem/repositories.py
  wacruit/src/apps/problem/schemas.py
  wacruit/src/apps/problem/services.py
  wacruit/src/apps/recruiting/repositories.py
  wacruit/src/database/migrations/versions/2023_07_26_0022-79d431037047_recruiting.py
  wacruit/src/database/migrations/versions/2023_07_27_0017-a3cacde08168_testcase_resource.py
  wacruit/src/database/migrations/versions/2023_07_28_0025-6eb442d2b80e_fix_typo.py
  wacruit/src/tests/problem/conftest.py
  wacruit/src/tests/recruiting/conftest.py
Labels: enhancement, fix
